name: Build EXE (Windows 7 Compatible)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8 (Windows 7 Compatible)
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas fpdf pyqt5

      - name: Build EXE for Windows 7
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py
          dir dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BankSoalApp-Win7
          path: dist/BankSoalApp.exe
